### ISSUE TITLE
missing appmaster in install

### ISSUE THREAD

**Issue by furushchev** [PR2/app_manager#1]
@TheDash 
I wonder why this repository has `appmaster` executable in `bin` directory, which is omitted to install in CMakeLists.txt.
This program is indispensable for users.

**Comment by UltronDestroyer** [comment]
I overlooked that. When I catkinized these, I made a tool to help which was an add-on of the catkinized package tool. So.. The old install to bin directory from fuerte was still carried over ;-). Needs to be fixed though.

**Comment by furushchev** [comment]
so we should fix since it is already released.
