### ISSUE TITLE
Release request: 1.1.1

### ISSUE THREAD

**Issue by knorth55** [PR2/app_manager#12]
We need this commit to install `launch` dir correctly.
Also, latest kinetic version is `1.0.5`, and we need `1.1.1` for kinetic, too.
https://github.com/PR2/app_manager/commit/7fa0929b6608246073a0fb89eed013edd6b934ca

**Comment by knorth55** [comment]
@Kanazawanaoaki

**Comment by k-okada** [comment]
sorry for super late, released https://github.com/ros/rosdistro/pull/24459, https://github.com/ros/rosdistro/pull/24460

**Comment by knorth55** [comment]
Thank you!
