### ISSUE TITLE
Can't run jog_control launch file.

### ISSUE THREAD

**Issue by lutecia16v** [PR2/app_manager#13]
Hello everyone,

I am on Ubuntu 18.04 LTS with ROS Melodic.
When I try to run jog_control(https://github.com/tork-a/jog_control) launch file using app_manager like below, but it can't.

```
$ rosservice call /robot/start_app jog_launch/i611
started: False
error_code: 500
message: "internal error [signal only works in main thread]"
namespace: ''
```

This is my .app file: 

``` i611.app
display: i611 Jog launch
description: i611 Jog launch
platform: i611
launch: jog_launch/i611.launch
```

Perhaps jog_control use SIGNAL function in it, but I think it is not special case.
Is it a limitation to use app_manager? Are there any way to run these launch file?

Thanks a lot.

**Comment by k-okada** [comment]
Thank you for report, can you explain more about how to reproduce this? For example can you provide .rosinstall file or upload entire workspace? So that I do not have to write .app file by myself?

**Comment by k-okada** [comment]
@lutecia16v please look at https://github.com/k-okada/jog_control/tree/add_app, and start `app_manager` by `roslaunch app_manager app_manager.launch`
You can run UR5 demo by `rosservice call /robot/start_app jog_launch/ur5`
