### ISSUE TITLE
Release app_manager to ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [PR2/app_manager#21]
Would you mind releasing `app_manager` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 16 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by v4hn** [comment]
@k-okada could you take care of PR2 package releases for noetic?

**Comment by davefeilseifer** [comment]
I just did a pre-release test and it passed. Should be ready for release:

generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   noetic default ubuntu focal amd64   --custom-repo          willow_maps__custom-19:git:https://github.com/PR2/willow_maps.git:kinetic-devel app_manager__custom-17:git:https://github.com/PR2/app_manager.git:kinetic-devel  --level 0   --output-dir ./

**Comment by k-okada** [comment]
@davefeilseifer thanks for checking, released https://github.com/ros/rosdistro/pull/28463
