### ISSUE TITLE
just an idea: function of displaying doc of demo with rosservice

### ISSUE THREAD

**Issue by takayuki5168** [PR2/app_manager#8]
We can execute some demos as apps with this app_manager. But sometimes there are many procedures to do demo. For example, when we want to [diabolo demo](https://github.com/takayuki5168/jsk_diabolo_pr2), we have to know what we prepare(designated diabolo and its sticks), how PR2 hold sticks(with our help? or not), ...

So I think that each demo there should be a doc to write what we prepare, what to help or what to attend when executing demo. I want each app have doc.md, and we can read it with rosservice like `rosservice call doc_app diabolo` or with raw markdown file. With this, one who is not so new to one demo, he can execute it with this doc.

**Comment by v4hn** [comment]
This is such an awesome demo! :D

I'm not sure how helpful such a service call would really be.
For a graphical app manager a text that is automatically displayed for the app might make sense.

I believe it is very challenging to give enough information in such a text so someone else might perform the demo without being instructed.
Photos would simplify this a lot, but then you require full html-support (or interpreted markup) which makes more sense outside the ROS system.

So I would propose to leave this out of the app manager itself, but encourage you to write good documentation in rosdoc/[rosdoc_lite](http://wiki.ros.org/rosdoc_lite).

**Comment by takayuki5168** [comment]
Thanks. This is one of juggling and one of my hobby :)

I appreciate your kind comments. I will refer those.
